title: kim seojin Security Portfolio
author: kimseojin
email: cc4391@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Showcasing the security projects I have worked on.

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed
